#! /bin/sh

export TESTDATA=$(dirname $0)/test-data

if [ -z "$TESTPROG" ]; then
  TESTPROG=test
fi

if [ "$1" = -g ]; then
  gdb="libtool --mode=execute gdb --args"
  shift
else
  gdb=""
fi

$gdb ./$TESTPROG $(basename $1 | sed s/-/_/g)
