#! /bin/sh

./reset-db

# Install gnome from stable
./dpm-tool --db dpm.db --origin stable force-install libc6
./dpm-tool --db dpm.db --origin stable install gnome

# Upgrade it to testing
./dpm-tool --db dpm.db --origin testing install gnome=1:2.30+11
./dpm-tool --db dpm.db --origin testing force-install libc6
./dpm-tool --db dpm.db --origin testing install gnome=1:2.30+11
./dpm-tool --db dpm.db --origin testing force-install perl
./dpm-tool --db dpm.db --origin testing install gnome=1:2.30+11
