#! /bin/sh

cmd () {
    echo
    echo "+++ " $@
    echo
    "$@"
}

./reset-db

# Install gnome from stable
cmd ./dpm-tool --db dpm.db --origin stable install gnome

# Upgrade it to testing
cmd ./dpm-tool --db dpm.db --origin testing install gnome=1:2.30+11
